name: Trigger Vercel Endpoint

on:
  schedule:
    - cron: '0 23 * * *'  # Every day at 11 PM UTC, which is 8 AM Seoul time
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  trigger-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel API Endpoint
        run: |
          curl -X POST "https://tinynotie-api.vercel.app/openai/getKoreanWords" \
          -H "Content-Type: application/json"
